# Generated by Django 2.2 on 2019-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nane', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reject', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
