# Generated by Django 2.2 on 2019-04-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='nane',
            new_name='name',
        ),
    ]
